language: cpp

os: osx
osx_image: xcode9.3beta
compiler: gcc
before_install:
# - brew update # takes alot of time =(
 - brew upgrade cmake
install: true 
script:
 - git clean -df 
 - cmake -configure experiments/01_01_eclipse/  # configure project
 - cmake -generate experiments/01_01_eclipse/   # generate project
 - make                                         # build generated project
 - ./eclipse_first_run                          # run
 
 - git clean -df
 - mkdir build
 - cd build
 - mkdir nolib
 - cd nolib
 - cmake -configure ../../experiments/01_02_make_lib/
 - cmake -generate ../../experiments/01_02_make_lib/
 - make -j 4
 - chmod a+x ./use_lib
 - ./use_lib
 - ./use_lib Daniil
 - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./use_lib"
          
 - git clean -df
 - cd ../
 - mkdir uselib
 - cd uselib
 - cmake -configure -DHELLOLIB=ON ../../experiments/01_02_make_lib
 - cmake -generate ../../experiments/01_02_make_lib
 - make -j 4
 - chmod a+x ./use_lib
 - ./use_lib
 - ./use_lib Daniil
 
 - git clean -df