language: cpp

os: osx
osx_image: xcode9.3beta
compiler: gcc
before_install:
 - brew upgrade cmake
install:
 - brew install sdl2 # for some reasons, I have the issues with linking with SDL2's dylib that built from source, so install it from Homebrew
 - brew install gzip
script:
 - git clean -df
 
 - mkdir build && cd build
 - cmake ${SOURCE_FOLDER_PATH}/04_01_opengl_min
 - make -j 4
 - ./${OSX_EXEC_NAME} 1 # pass the parameter to force-escape from the main game loop
 - chmod +x ${OSX_EXEC_NAME}
 - gzip -k -9 -N ${OSX_EXEC_NAME}
 - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./${OSX_EXEC_NAME}.gz" # upload
 
 - git clean -df
