language: cpp

os: osx
osx_image: xcode9.3beta
compiler: gcc
before_install:
# - brew update # takes alot of time =(
 - brew upgrade cmake
install:
 - brew install sdl2 # for some reasons, I have the issues with linking with SDL2's dylib that built from source, so install it from Homebrew
script:
 - git clean -df
 - mkdir build && cd build
 - cmake -DCMAKE_BUILD_TYPE=Release ../experiments/03_01_main_loop
 - make -j 4
 - chmod a+x ./mainloop_osx
 - ./mainloop_osx 1 # pass the parameter to force-escape from the main game loop
 - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./mainloop_osx" # upload
 
 - git clean -df