language: cpp

os: osx
osx_image: xcode9.3beta
compiler: gcc
before_install:
 - brew upgrade cmake
install:
 - brew install sdl2 # for some reasons, I have the issues with linking with SDL2's dylib that built from source, so install it from Homebrew
script:
 - git clean -df
 
 - mkdir build && cd build
 - cmake -DCMAKE_BUILD_TYPE=Release ../experiments/03_02_main_loop_to_engine
 - make -j 4
 - ./microengine_osx 1 # pass the parameter to force-escape from the main game loop
 - chmod +x microengine_osx
 - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./microengine_osx" # upload
 
 - git clean -df
