# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:7.2

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt-get update # update repo indeces
          - apt-get install -y cmake # install cmake
          
          - git clean -df 
          - cmake -configure experiments/01_eclipse/ # configure project
          - cmake -generate experiments/01_eclipse/ # generate project
          - make # build generated project
          - ./eclipse_first_run # run build by name of CMake project inside of CMakeLists.txt
          
          - git clean -df
          - cmake -configure experiments/02_make_lib/
          - cmake -generate experiments/02_make_lib/
          - make
          - ./bin/using_lib
          - ./bin/using_lib Daniil
          - ./bin/using_lib Alexey
          - ./bin/using_lib Leonid
          - ./bin/using_lib Bad example