image: gcc:7.2

pipelines:
  custom: # Let's make it runs manually only...
    manual:
      - step:
          script:
            - apt-get update # update repo indeces
            - apt-get install -y cmake # install cmake
            - apt-get install sdl2
            
            - git clean -df
            - mkdir build && cd build
            - cmake -DCMAKE_BUILD_TYPE=Release ../experiments/03_01_main_loop
            - make -j 4
            - ./mainloop_linux 1 # pass the parameter to force-escape from the main game loop
            - chmod a+x ./mainloop_linux
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./mainloop_linux" # upload
 
            - git clean -df